### ISSUE TITLE
[Feature] - 마이 페이지 UI 수정

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#103]
## ✏️Description
- 마이페이지와 관련된 페이지들의 UI를 수정합니다.

## ✅TODO
- 마이페이지 
- [ ] 마이페이지 메인 (상태 바 조건부 렌더링)
- [ ] 내 정보 수정 - 회원 탈퇴 UI 수정
- [ ] 알림 페이지 구현 
- [ ] 문의사항 페이지 수정 
- [ ] 전체적으로 정렬 일정하게 맞추도록
