### ISSUE TITLE
[Feature] - 검색 관련 페이지 UI구현

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#104]
## ✏️Description
- 검색 관련 페이지의 UI 구현을 수정하고, 완료합니다.

## ✅TODO
- [ ] 태그 통일해서 UI 일관성 유지
- [ ] 검색 -> 검색 결과 리스트 -> 검색 기업 상세보기 -> 질문 상세보기 한 플로우 유연하게 움직이는지 확인
- [ ] 위의 플로우에서 뒤로가기 잘 되는지 확인 (Prev)
- [ ] 중간 페이지에서 로그인 해보고, 페이지 이동 오류 없는지 확인
- [ ] API 연결해서 직접 화면 보기
- [ ] height: 100vh; 오류 수정
