### ISSUE TITLE
[Feature] 라우터 설정

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#13]
## ✏️Description
**Router 설정하여 화면에 jsx 파일들이 보이게끔 설정**

## ✅TODO
- [x] allRouter > allRouter.js
- [x] exact componet X, element
- [x] Router로 반드시 감싸주기
