### ISSUE TITLE
[Feature] - 상점 페이지 UI 구현

### ISSUE THREAD

**Issue by JayJayleee** [COFLLL/CoverFlow-FE#144]
## ✏️Description
상점 페이지 UI를 구현합니다.

## ✅TODO
- [ ] 상점 페이지 내 붕어빵 구매 탭 UI
- [ ] 상점 페이지 내 붕어빵 구매 내역 UI
- [ ] 결제 완료 페이지 UI 구현
