### ISSUE TITLE
[Feature] 기업 검색 기능

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [COFLLL/CoverFlow-FE#151]
## ✏️Description
- 기업 검색 기능 구현

## ✅TODO
- [x] 검색 디바운스 구현
- [x] 검색어 자동완성
- [x] 검색 결과 노출시키기
- [x] 기업 상세 페이지
