### ISSUE TITLE
[Feature] - 질문 등록 및 기업 상세 UI 개선

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [COFLLL/CoverFlow-FE#191]
## ✏️Description
- 질문 등록 및 기업 상세 UI를 개선하여 반영합니다.

## ✅TODO
- [x] 기업 상세 페이지
- [x] 질문 등록 페이지
- [x] 질문 상세 페이지
