### ISSUE TITLE
[BugFix] - 실시간 알림 UI 연동 및 유효한 토큰 업데이트

### ISSUE THREAD

**Issue by JayJayleee** [COFLLL/Coverflow-FE#271]
## 🗺️Location
- 실시간 알림 내 bugfix

## 🤷WHAT / WHY
- SSE 만료 주기와 토큰 만료주기가 맞물려 토큰이 유효하지 않아 에러 발생하는 이슈

## ✅TODO

- [x] 로그인 /로그아웃 시 실시간 알람 연동되도록 로직 수정
- [x] 메인화면 인풋 창 위치 조정
- [x] 상점 페이지 탭바 색상 변경 안되는 이슈 수정
- [x] #273
- [x] 알림 페이지 무한스크롤 적용
