### ISSUE TITLE
[Feature] - 베타 테스트 피드백 적용

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [COFLLL/Coverflow-FE#290]
## ✏️Description
- 베타 테스트

## ✅TODO
- [x] 기업 상세 페이지 내 질문 리스트에서 붕어빵 개수 컬러 수정
- [x] 질문 카테고리 보여주는 방식 수정
- [x] 회사이름 길이에 따라 줄바꿈 되는 현상 수정
- [x] 질문 등록시 모든 필드가 채워져 있지 않았을 때, '에러발생 :Error' 수정
- [x] 질문 카테고리 추가
- [x] 현업자 == 갈색 나무 / 취준생 == 초록 이파리 수정
- [x] 질문 상세 페이지에서 기업 태그에 있는 하얀색 글씨 수정
- [x] 답변 input 창  피그마대로 다시 수정
- [x] 답변 디자인 수정
- [x] 답변이 없는 경우에도 페이지네이션 화살표가 나옵니다.(히든 처리 필요)
- [x] 기업 상세 페이지 내 질문 리스트 box-shadow로 수정
- [x] 기업 상세 페이지에서 질문 태그 선택했을 때, 폰트 굵기와 색상 바꾸기
- [x] 클릭 했을 때의 이벤트 css는 개발 서버 피드백 페이지 참고, 피그마에도 선택되었을 때의 디자인이 어때야되는지 나와있습니다. 
- [x] 기업 상세 페이지 내 구분선 회색 아니고, #FFF9F4 / stroke : 5px입니다. 
- [x] 질문 작성자가 해당 질문에 답변을 남기려고 할 시 오류나는 부분 수정 → 비속어로 답변 남길 시 에러 발생. 토스트로 변경 필요
- [x] 질문 등록 내 textarea 크기 조정 방지하기
- [x] 신고  UI 수정 및 질문에 대해 신고하면,공백일 수 없습니다. 라는 에러코드 나옴
