### ISSUE TITLE
[Feature] - 성별 및 연령대 카테고리 필터 구현

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#34]
## ✏️Description
**성별 및 연령대 카테고리 필터 구현**

## ✅TODO
- [x] 카테고리 필터 구현
- [x] 성별 및 연령대 옆 (선택) 문구 추가
- [x] 필터 하나를 선택한 경우, 다른 필터 해제
