### ISSUE TITLE
[Feature] - 닉네임 유효성 검사 및 중복 체크

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#35]
## ✏️Description
**닉네임 유효성 검사 및 중복 체크**

## ✅TODO
- [ ] 정규표현식을 통한 닉네임 유효성 검사
- [ ] 중복 검사 버튼 UI 제작
- [ ] 버튼 클릭 시, 닉네임 중복 검사 진행 이벤트 
- [ ] 중복 검사 결과 반환 
- [ ] 중복 검사 진행하지 않고 아래 항목 체크 시, 중복 검사 요청 모달 창
