### ISSUE TITLE
[Feature] - 토큰 디코딩 구현

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#49]
## ✏️Description
- api를 이용하여 토큰을 수신하고, 수신이 되었는지 확인합니다.
- 토큰의 유무에 따라 사용자를 구분하고, 각각 다른 페이지로 리다이렉트 시킵니다.
- 토큰을 디코딩 합니다.

## ✅TODO
- [ ] 토큰 디코딩 [base64]
- [ ] 토큰 수신 및 확인
- [ ] 사용자 역할 별 리다이렉트
