### ISSUE TITLE
[Feature] - 로그인 전체 과정 체크

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#64]
## ✏️Description
- 로그인 전 과정을 체크합니다.

## ✅TODO
- [x] 태그에 호버 시, 색 변경
- [x] 태그 두 번 눌렀을 때 취소
- [x] 로그인 성공하고, 메인으로 돌아갔을 때, user.svg 파일로 변경
- [x] 체크 버튼 선택 시, 시작하기 버튼 색 변경
- [x] 시작하기 버튼 눌렀을 때, 데이터 이동 확인 
- [x] 태그 데이터 이동 시, "취준생" "현직자"로 갈 수 있도록!
