### ISSUE TITLE
[Feature] - 로그인과 연결되는 페이지 수정

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#79]
## ✏️Description
- 로그인과 연결되는 페이지 수정합니다.

## ✅TODO
- [x] 마이페이지 -> 로그인 성공 시, 열림
- [x] 알림페이지 -> 로그인 성공 시, 열림 
- [x] 유저 아이콘 배경색 지우고, 위치 조정
- [x] 유저 아이콘 클릭 시, 마이페이지 연결
- [x] 마이페이지에 간단한 로그아웃 버튼 만들어서 로그아웃 구현
