### ISSUE TITLE
[Feature] - ESlint & Prettier 설정

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#8]
## ✏️Description
**코드의 일관성과 가독성을 위해 ESlint와 Prettier를 적용합니다.**

## ✅TODO
- [x] Prettier 설치 및 설정
- [x] ESlint 설치 및 설정
- [x] vscode 내에 있는 Prettier, ESlint extension 설치
