### ISSUE TITLE
[Feature] - 메인 / 마이페이지 UI 구현

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#83]
## ✏️Description
- 메인페이지 상단 UI (=Header)를 수정합니다.
- 마이페이지 UI를 구현합니다.

## ✅TODO
- [x] 유저 아이콘 호버 시, Cursor : pointer
- [x] 유저 아이콘 클릭 시, 드롭다운 메뉴 창
- [x] 드롭다운 외부를 클릭했을 때, 드롭다운 종료
- [x] 붕어빵 아이콘 + 잔여 개수 띄우기
- [x] 붕어빵 아이콘 클릭 시, 상점 이동 
- [x] 마이페이지에 유저 닉네임 불러오기 + 붕어빵 개수 보여주기
- [x] 로그아웃 로직 수정 ( 로그아웃 api 호출 +리프레시 토큰 삭제 로직 )
