### ISSUE TITLE
[Feature] - 검색 기능 연결

### ISSUE THREAD

**Issue by raxchaz** [COFLLL/CoverFlow-FE#88]
## ✏️Description
- 검색 기능 API를 연결합니다.

## ✅TODO
- [x] 검색 인풋 창에 검색어를 입력하고, 검색버튼을 누르면 서버로 데이터가 전송
- [ ] 검색 목록 창 UI 개발 및 구현
- [x] 검색 결과 없음 UI 개발

## 🐾ETC
아무것도 입력하지 않고 검색을 눌렀을 때, 검색 결과가 없다는 페이지를 띄울지
아니면, 아무것도 입력하지 않고 검색했을 때, 검색어를 입력하라는 알러트창을 띄울지!
